### ISSUE TITLE
LBANN does not build with Aluminum v0.2: error: 'AllreduceAlgorithm' is not a member of 'Al'

### ISSUE THREAD

**Issue by mxmlnkn** [LLNL/lbann#870]
in this [commit](https://github.com/LLNL/Aluminum/commit/8998784b2fe2bbfeec8497043d938968df5a9cfd), the Aluminum interface seems to have been changed. My LBANN build with Aluminum activated fails because of this:

    [  1%] Built target LbannProto
    make -f CMakeFiles/lbann.dir/build.make CMakeFiles/lbann.dir/depend
    make[2]: Entering directory '/opt/lbann-0.97.1/spack_builds/singularity'
    cd /opt/lbann-0.97.1/spack_builds/singularity && /opt/cmake/bin/cmake -E cmake_depends "Unix Makefiles" /opt/lbann-0.97.1 /opt/lbann-0.97.1 /opt/lbann-0.97.1/spack_builds/singularity /opt/lbann-0.97.1/spack_builds/singularity /opt/lbann-0.97.1/spack_builds/singularity/CMakeFiles/lbann.dir/DependInfo.cmake --color=
    Scanning dependencies of target lbann
    make[2]: Leaving directory '/opt/lbann-0.97.1/spack_builds/singularity'
    make -f CMakeFiles/lbann.dir/build.make CMakeFiles/lbann.dir/build
    make[2]: Entering directory '/opt/lbann-0.97.1/spack_builds/singularity'
    [  2%] Building CXX object CMakeFiles/lbann.dir/src/callbacks/callback_check_dataset.cpp.o
    /usr/bin/g++  -Dlbann_EXPORTS -I/opt/lbann-0.97.1/spack_builds/singularity -I/opt/lbann-0.97.1/include -isystem /opt/lbann-0.97.1/spack_builds/singularity/src/proto -isystem /opt/spack-0.12.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/protobuf-3.5.2-hoczob3u4sx7wpagddalzjakdnr32kim/include -isystem /opt/spack-0.12.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/zlib-1.2.11-av3mmgf66zwic2i34n7o2oxtp4quy6pi/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /opt/Elemental/include -isystem /opt/Elemental/include/El -isystem /opt/Aluminum/include/aluminum -isystem /opt/hwloc/include -isystem /usr/local/cuda/include -isystem /usr/local/cuda-10.0/targets/x86_64-linux/include/thrust/system/cuda/detail -isystem /opt/spack-0.12.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/opencv-3.4.3-w7c5rgdm6ufmpr4a2jad6c4fgk5y34nf/include -isystem /opt/spack-0.12.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/opencv-3.4.3-w7c5rgdm6ufmpr4a2jad6c4fgk5y34nf/include/opencv -isystem /opt/cnpy/include  -DLBANN_SET_EL_RNG -ldl -fPIC -g -Wall -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -Wshadow -O3 -DNDEBUG -fPIC   -fopenmp -std=gnu++11 -o CMakeFiles/lbann.dir/src/callbacks/callback_check_dataset.cpp.o -c /opt/lbann-0.97.1/src/callbacks/callback_check_dataset.cpp
    In file included from /opt/lbann-0.97.1/include/lbann/utils/summary.hpp:35:0,
                     from /opt/lbann-0.97.1/include/lbann/callbacks/callback.hpp:33,
                     from /opt/lbann-0.97.1/include/lbann/callbacks/callback_check_dataset.hpp:31,
                     from /opt/lbann-0.97.1/src/callbacks/callback_check_dataset.cpp:28:
    /opt/lbann-0.97.1/include/lbann/comm.hpp: In member function 'void lbann::lbann_comm::allreduce(T*, int, T*, El::mpi::Comm, El::mpi::Op)':
    /opt/lbann-0.97.1/include/lbann/comm.hpp:675:11: error: 'AllreduceAlgorithm' is not a member of 'Al'
         ::Al::AllreduceAlgorithm algo = ::Al::AllreduceAlgorithm::automatic;
               ^~~~~~~~~~~~~~~~~~
    /opt/lbann-0.97.1/include/lbann/comm.hpp:675:11: note: suggested alternative: 'MPIAllreduceAlgorithm'
         ::Al::AllreduceAlgorithm algo = ::Al::AllreduceAlgorithm::automatic;
               ^~~~~~~~~~~~~~~~~~
               MPIAllreduceAlgorithm
    /opt/lbann-0.97.1/include/lbann/comm.hpp:678:85: error: 'algo' was not declared in this scope
           snd, rcv, count, mpi_op_to_al_op(op), c.template GetComm<::Al::MPIBackend>(), algo);
                                                                                         ^~~~
    /opt/lbann-0.97.1/include/lbann/comm.hpp:678:85: note: suggested alternative: 'auto'
           snd, rcv, count, mpi_op_to_al_op(op), c.template GetComm<::Al::MPIBackend>(), algo);
                                                                                         ^~~~
                                                                                         auto
    /opt/lbann-0.97.1/include/lbann/comm.hpp: In member function 'void lbann::lbann_comm::allreduce(T*, int, El::mpi::Comm, El::mpi::Op)':
    /opt/lbann-0.97.1/include/lbann/comm.hpp:694:11: error: 'AllreduceAlgorithm' is not a member of 'Al'
         ::Al::AllreduceAlgorithm algo = ::Al::AllreduceAlgorithm::automatic;
               ^~~~~~~~~~~~~~~~~~
    /opt/lbann-0.97.1/include/lbann/comm.hpp:694:11: note: suggested alternative: 'MPIAllreduceAlgorithm'
         ::Al::AllreduceAlgorithm algo = ::Al::AllreduceAlgorithm::automatic;
               ^~~~~~~~~~~~~~~~~~
               MPIAllreduceAlgorithm
    /opt/lbann-0.97.1/include/lbann/comm.hpp:697:81: error: 'algo' was not declared in this scope
           data, count, mpi_op_to_al_op(op), c.template GetComm<::Al::MPIBackend>(), algo);
                                                                                     ^~~~
    /opt/lbann-0.97.1/include/lbann/comm.hpp:697:81: note: suggested alternative: 'auto'
           data, count, mpi_op_to_al_op(op), c.template GetComm<::Al::MPIBackend>(), algo);
                                                                                     ^~~~
                                                                                     auto
    CMakeFiles/lbann.dir/build.make:65: recipe for target 'CMakeFiles/lbann.dir/src/callbacks/callback_check_dataset.cpp.o' failed
    make[2]: *** [CMakeFiles/lbann.dir/src/callbacks/callback_check_dataset.cpp.o] Error 1
    make[2]: Leaving directory '/opt/lbann-0.97.1/spack_builds/singularity'
    CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/lbann.dir/all' failed
    make[1]: *** [CMakeFiles/lbann.dir/all] Error 2
    make[1]: Leaving directory '/opt/lbann-0.97.1/spack_builds/singularity'
    Makefile:132: recipe for target 'all' failed
    make: *** [all] Error 2

The underlying problem is that even with the docker, singularity file, the Readme.md, the BuildingLBANN.md, and spack, I was not able to find out the correct version to use for Aluminum ... spack for example simple lists "Aluminum@master" as dependency.

**Comment by ndryden** [comment]
We didn't start versioning Aluminum until recently, unfortunately (my fault, sorry about that).

@bvanessen I think we need to bump the version of LBANN in Spack, and then have it use the v0.2 release of Al.

**Comment by bvanessen** [comment]
Yes, I will bump up LBANN.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by bvanessen** [comment]
@ndryden I have bumped up LBANN to v0.98.  We can test out the new #857 and then look at bumping up the requirements for LBANN to go to Aluminum v0.2

**Comment by ndryden** [comment]
@bvanessen #857 is already tested.

**Comment by bvanessen** [comment]
Okay I will look at merging it tonight.


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Feb 9, 2019, at 4:55 AM, Nikoli Dryden <notifications@github.com<mailto:notifications@github.com>> wrote:


@bvanessen<https://github.com/bvanessen> #857<https://github.com/LLNL/lbann/pull/857> is already tested.

**Comment by mxmlnkn** [comment]
I think with the release of v0.98.1 this has been solved. At least, I'm successfully compiling it in the [singularity image](https://github.com/LLNL/lbann/issues/855#issuecomment-462073056).
